language: node_js
node_js:
  - "4.1"
before_install: npm install -g webpack jasmine
install: npm install
before_script: npm test
script: webpack --config webpack.dist.conf.js && chmod +x ./deploy-ghpages.sh && npm run deploy 
env:
    global:
    - GH_REF: github.com/MayasHaddad/henri-potier.git
    - secure: EQH/3Be0vxyF4kOkxrPOJrvZXvcM38sobZ4f3rsULzdwfNNXHQrmaqSSWYN5TDSjTb7klqky50E4os7ISdUa6xWdkJuKucCWxnAnpC7Y7CdUbqkoOKI50CLunPrlEuTRGAumoKyCNxg17nC1tDhfk31pge9q9Omm4hxDz9LWVbbyzO1wruL6c08dXME7xfspuveXFHD3scSKPnaQls+gTqrqh++yM/DKh4+rFMZ1nca/OijWJIF1LDfJTbfx2yIJj0UZpL+iGjxojp54myGY2MWF7ViV4AYEovim3xmzIZMi/uhnQEeea4C8jppDjsrObIJkxk9SqfBFpjyf2cNUvpkc4sM0GnJE0VM6KauI0oFY0VYBIH2pGnHgiMMN3Q+SR91SjKQcQZTHJgFwPgdBXnzLxAyzqeF8Gt/xgrXk78nqXoGR1iAwQVR8PPeS6L7RD2OCFlnISuWJuCjiSgjZipXIFZO7xUGNjsrgTJ/fOjLEU5eIwR/xqOimoxp8Y7lNiL8TnnzzoqrKAG+Qu2ZzPbgfOH1ntazqWwSJGM4p0LIcORq6S3Xo4vHE4I34u2krNTcYtRb9rGnukSLuOCgvQkfs0i2FBIfv+pXgP6ioBlS0tUfWI9m2lx7XLtDcviV3EpEBXjOZSBqwZ9CmY+w/49QrmQEcD6o2zaWVDCQtNTw=